[package]
name = "mcsl_future_web"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
env_logger = "0.11.8"
include_dir = "0.7"
log = "0.4.28"
mime_guess = "2.0.5"
serde_json = "1.0.145"
serde = {"version" = "1.0.145", features = ["derive"]}
