# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # App
  - package-ecosystem: 'npm'
    directory: '/apps/app'
    schedule:
      interval: 'weekly'

  # Web
  - package-ecosystem: 'npm'
    directory: '/apps/web'
    schedule:
      interval: 'weekly'

  # Shared
  - package-ecosystem: 'npm'
    directory: '/package/shared'
    schedule:
      interval: 'weekly'

  # UI
  - package-ecosystem: 'npm'
    directory: '/package/ui'
    schedule:
      interval: 'weekly'

  # Configs
  - package-ecosystem: 'npm'
    directory: '/package/configs'
    schedule:
      interval: 'monthly'
